name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^2.0.5
  get: ^4.6.5
  responsive_framework: ^0.2.0
  otp_text_field: ^1.1.3
  table_calendar: ^3.0.9
  rating_summary: ^1.0.2+1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.1.1
  dartz: ^0.10.1






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
 


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:

    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Medium.ttf

  
         
   